const {test}=require('node:test');
const assert=require('node:assert/strict');
const {Game,xFor,yFor}=require('../engine.js');
function tick(g,t){for(let i=0;i<Math.ceil(t*120);i++)g.update(1/120);}
function fresh(){const g=new Game(42);g.start();return g;}
test('discrete motion, boundaries, and one-time distance score',()=>{const g=fresh();g.cars=[];g.lanes=[];assert.equal(g.movePlayer(0,-1),true);assert.equal(g.movePlayer(0,-1),false);tick(g,.11);assert.equal(g.player.row,10);assert.equal(g.player.y,yFor(10));const score=g.score;g.movePlayer(0,1);tick(g,.11);g.movePlayer(0,-1);tick(g,.11);assert.equal(g.score,score);g.player.col=0;g.player.x=xFor(0);assert.equal(g.movePlayer(-1,0),false);});
test('traffic moves, wraps, and stays bounded through long sessions',()=>{const g=fresh();const n=g.cars.length,x=g.cars[0].x;tick(g,.2);assert.notEqual(g.cars[0].x,x);tick(g,300);assert.equal(g.cars.length,n);assert.ok(g.cars.every(c=>Number.isFinite(c.x)&&Math.abs(c.x)<2500));});
test('collision costs exactly one life and respawns at checkpoint',()=>{const g=fresh();g.checkpoint=6;g.invulnerable=0;g.player={col:7,row:10,x:xFor(7),y:yFor(10)};g.cars=[{x:xFor(7),y:yFor(10),w:90,dir:1}];g.lanes=[];tick(g,.01);assert.equal(g.lives,2);tick(g,.3);assert.equal(g.lives,2);tick(g,.7);assert.equal(g.player.row,6);assert.ok(g.invulnerable>0);});
test('both strain pickups and inventory limit work',()=>{const g=fresh();g.pickups=[{col:7,row:11,kind:'taxi'},{col:7,row:11,kind:'apollo'},{col:7,row:11,kind:'taxi'}];g.collect();assert.deepEqual(g.inventory,['taxi','apollo']);assert.equal(g.pickups[2].collected,undefined);assert.equal(g.score,300);});
test('Dirty Taxi stops and then releases traffic',()=>{const g=fresh();g.inventory=['taxi'];g.activate();const x=g.cars[0].x;tick(g,2);assert.equal(g.cars[0].x,x);tick(g,3);assert.notEqual(g.cars[0].x,x);assert.equal(g.inventory.length,0);});
test('Apollo 13 protects then expires',()=>{const g=fresh();g.invulnerable=0;g.inventory=['apollo'];g.activate();assert.equal(g.hit(),false);tick(g,5.2);assert.equal(g.hit(),true);assert.equal(g.lives,2);});
test('pause freezes movement, traffic, and strain timers',()=>{const g=fresh();g.inventory=['taxi'];g.activate();g.pause();const x=g.cars[0].x,t=g.effects.taxi;tick(g,4);assert.equal(g.effects.taxi,t);assert.equal(g.cars[0].x,x);assert.equal(g.movePlayer(0,-1),false);g.pause();assert.equal(g.state,'playing');});
test('successful crossing progresses and awards repair every third run',()=>{const g=fresh();g.cars=[];g.lanes=[];for(let i=0;i<11;i++){g.movePlayer(0,-1);tick(g,.12);}assert.equal(g.state,'complete');assert.ok(g.score>1000);g.nextLevel();assert.equal(g.level,2);assert.equal(g.state,'playing');assert.equal(g.lanes.length,7);g.level=3;g.lives=2;g.complete();assert.equal(g.lives,3);});
test('game-over and clean restart',()=>{const g=fresh();for(let i=0;i<3;i++){g.invulnerable=0;g.deathTimer=0;g.hit();}assert.equal(g.state,'gameover');g.start();assert.equal(g.state,'playing');assert.equal(g.lives,3);assert.equal(g.score,0);assert.equal(g.level,1);});
test('close calls reward once, combo expires, and 420 doubles score',()=>{const g=fresh();g.invulnerable=0;g.lanes=[];g.player.y=yFor(10);g.cars=[{x:g.player.x+70,y:g.player.y,w:80,dir:1,near:false,passed:false}];tick(g,.02);assert.equal(g.cars[0].near,true);g.cars[0].x+=20;tick(g,.02);assert.equal(g.stats.close,1);const points=g.score;tick(g,.2);assert.equal(g.score,points);tick(g,5.1);assert.equal(g.combo,1);g.startEvent('420');const before=g.score;g.addScore(100);assert.equal(g.score-before,200);});
test('twenty stages preserve meaningful minimum gaps and finite velocities',()=>{const g=fresh();for(let level=1;level<=20;level++){g.level=level;g.makeLevel();for(const lane of g.lanes){assert.ok(lane.gap>=125);assert.ok(lane.speed<210);assert.ok(lane.cars.length>=3);}}});
